// cross reference link in an AsciiDoc table cell should resolve to reference in main document
== Some

|===
a|See <<_more>>
|===

== More

content

// AsciiDoc content
[cols="1e,1,5a"]
|===
|Name |Backends |Description

|badges |xhtml11, html5 |
Link badges ('XHTML 1.1' and 'CSS') in document footers.

[NOTE]
====
The path names of images, icons and scripts are relative path
names to the output document not the source document.
====
|[[X97]] docinfo, docinfo1, docinfo2 |All backends |
These three attributes control which document information
files will be included in the the header of the output file:

docinfo:: Include `<filename>-docinfo.<ext>`
docinfo1:: Include `docinfo.<ext>`
docinfo2:: Include `docinfo.<ext>` and `<filename>-docinfo.<ext>`

Where `<filename>` is the file name (sans extension) of the AsciiDoc
input file and `<ext>` is `.html` for HTML outputs or `.xml` for
DocBook outputs. If the input file is the standard input then the
output file name is used.
|===

// should preserve leading indentation in contents of AsciiDoc table cell if contents starts with newline
|===
a|
$ command
a| paragraph
|===

// should discover anchor at start of cell and register it as a reference
The highest peak in the Front Range is <<grays-peak>>, which tops <<mount-evans>> by just a few feet.

[cols="1s,1"]
|===
|[[mount-evans,Mount Evans]]Mount Evans
|14,271 feet

h|[[grays-peak,Grays Peak]]
Grays Peak
|14,278 feet
|===
